import React, { useState } from "react";

export default function AI() {

  const [symptoms, setSymptoms] =
      useState("");

        const [result, setResult] =
            useState("");

              const analyzeDisease = () => {

                  const text =
                        symptoms.toLowerCase();

                            if (
                                  text.includes("خمول") ||
                                        text.includes("لا يأكل")
                                            ) {

                                                  setResult(`
                                                  🦠 المرض المحتمل:
                                                  برد أو عدوى تنفسية

                                                  💊 العلاج المقترح:
                                                  - مضاد حيوي
                                                  - تدفئة الطائر
                                                  - فيتامين سي
                                                        `);

                                                            }

                                                                else if (
                                                                      text.includes("إسهال") ||
                                                                            text.includes("اسهال")
                                                                                ) {

                                                                                      setResult(`
                                                                                      🦠 المرض المحتمل:
                                                                                      التهاب معوي

                                                                                      💊 العلاج المقترح:
                                                                                      - مضاد حيوي معوي
                                                                                      - تغيير المياه
                                                                                      - تنظيف القفص
                                                                                            `);

                                                                                                }

                                                                                                    else if (
                                                                                                          text.includes("ريش") ||
                                                                                                                text.includes("تساقط")
                                                                                                                    ) {

                                                                                                                          setResult(`
                                                                                                                          🦠 الحالة المحتملة:
                                                                                                                          تبديل ريش أو نقص فيتامينات

                                                                                                                          💊 المقترح:
                                                                                                                          - فيتامينات
                                                                                                                          - كالسيوم
                                                                                                                          - تغذية أفضل
                                                                                                                                `);

                                                                                                                                    }

                                                                                                                                        else {

                                                                                                                                              setResult(`
                                                                                                                                              🤖 لم أستطع تحديد المرض

                                                                                                                                              حاول كتابة أعراض أوضح
                                                                                                                                                    `);

                                                                                                                                                        }

                                                                                                                                                          };

                                                                                                                                                            return (
                                                                                                                                                                <div
                                                                                                                                                                      style={{
                                                                                                                                                                              padding: "20px",
                                                                                                                                                                                      minHeight: "100vh",
                                                                                                                                                                                              background:
                                                                                                                                                                                                        "linear-gradient(to bottom,#020617,#111827)",
                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                          >

                                                                                                                                                                                                                                <h1>
                                                                                                                                                                                                                                        🤖 الذكاء الاصطناعي
                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                      marginTop: "20px",
                                                                                                                                                                                                                                                                                backgroundColor:
                                                                                                                                                                                                                                                                                            "#1e293b",
                                                                                                                                                                                                                                                                                                      padding: "20px",
                                                                                                                                                                                                                                                                                                                borderRadius: "15px",
                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                              >

                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                placeholder="اكتب أعراض الطائر..."
                                                                                                                                                                                                                                                                                                                                                          value={symptoms}
                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                setSymptoms(
                                                                                                                                                                                                                                                                                                                                                                                              e.target.value
                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                      minHeight: "150px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={analyzeDisease}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "#8b5cf6",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🔍 تحليل الحالة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {result && (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "#065f46",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              whiteSpace: "pre-line",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          lineHeight: "2",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {result}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
}